TebLocalPlannerROS:
  odom_topic: odom
     
  # Trajectory
   
  teb_autosize: True
  dt_hysteresis: 0.1
  dt_ref: 0.5
  min_samples: 3
  global_plan_overwrite_orientation: True
  global_plan_viapoint_sep: 0.5
  max_global_plan_lookahead_dist: 3.0
  force_reinit_new_goal_dist: 1.0
  feasibility_check_no_poses: 5
  publish_feedback: False
  shrink_horizon_backup: True
  allow_init_with_backwards_motion: False #sdfsf
  exact_arc_length: False # note: had semicolon
     
  # Robot
          
  max_vel_x: 3.0
  max_vel_x_backwards: 3.0
  max_vel_theta: 4.0 #TODO: increase
  acc_lim_x: 6.0 #Maybe increase? 3.9 is the reasonable limit at half speed.
  acc_lim_theta: 6.0
  min_turning_radius: 0.0
  footprint_model: # types: "point", "circular", "two_circles", "line", "polygon"
    type: "circular"
    radius: 0.3 # for type "circular"
    #line_start: [-0.3, 0.0] # for type "line"
    #line_end: [0.3, 0.0] # for type "line"
    #front_offset: 0.2 # for type "two_circles"
    #front_radius: 0.2 # for type "two_circles"
    #rear_offset: 0.2 # for type "two_circles"
    #rear_radius: 0.2 # for type "two_circles"
    #vertices: [ [0.25, -0.05], [0.18, -0.05], [0.18, -0.18], [-0.19, -0.18], [-0.25, 0], [-0.19, 0.18], [0.18, 0.18], [0.18, 0.05], [0.25, 0.05] ] # for type "polygon"
    #vertices: [[-0.4927,-0.4985], [0.4927,-0.4985], [0.4927,0.4985], [-0.4927,0.4985]]

  # GoalTolerance
     
  xy_goal_tolerance: 0.3 #0.1
  yaw_goal_tolerance: 0.3 #0.05
  free_goal_vel: False
     
  # Obstacles
     
  min_obstacle_dist: 0.1
  include_costmap_obstacles: True
  costmap_obstacles_behind_robot_dist: 1.0 #5.0  
  obstacle_poses_affected: 20
  #inflation_dist: 0.6
  #legacy_obstacle_association: False
  #obstacle_association_force_inclusion_factor: 1.5
  #obstacle_association_cutoff_factor: 5.0
  costmap_converter_plugin: ""
  costmap_converter_spin_thread: True
  costmap_converter_rate: 5

  # Optimization
     
  no_inner_iterations: 4
  no_outer_iterations: 3
  optimization_activate: True
  optimization_verbose: False
  penalty_epsilon: 0.1

  weight_max_vel_x: 2
  weight_max_vel_theta: 1

  weight_acc_lim_x: 1 # set to zero to ignore acceleration limits
  weight_acc_lim_theta: 1

  weight_kinematics_nh: 1000
  weight_kinematics_forward_drive: 1
  weight_kinematics_turning_radius: 1

  weight_optimaltime: 1
  weight_obstacle: 50
  weight_inflation: 0.1
  weight_adapt_factor: 2.0
  weight_dynamic_obstacle: 10 # not in use yet
  selection_alternative_time_cost: False # not in use yet

  # Homotopy Class Planner

  enable_homotopy_class_planning: True
  enable_multithreading: True
  simple_exploration: False
  max_number_classes: 4
  roadmap_graph_no_samples: 15
  roadmap_graph_area_width: 5
  h_signature_prescaler: 0.5
  h_signature_threshold: 0.1
  obstacle_keypoint_offset: 0.1
  obstacle_heading_threshold: 0.45
  visualize_hc_graph: False

TrajectoryPlannerROS:
  # Robot Configuration Parameters

  acc_lim_theta: 6.0
  acc_lim_x: 3.0
  #acc_lim_y: 2.5

  max_vel_x: 6.096
  min_vel_x: 0.4
  max_rotational_vel: 3.14

  max_vel_theta: 3.14
  min_vel_theta: -3.14
  min_in_place_vel_theta: 0.5

  holonomic_robot: false
  escape_vel: -0.1

  # Goal Tolerance Parameters
  yaw_goal_tolerance: 0.1
  xy_goal_tolerance: 0.1
  latch_xy_goal_tolerance: false

  # Forward Simulation Parameters
  sim_time: 2.0
  sim_granularity: 0.04
  angular_sim_granularity: 0.02
  vx_samples: 6
  vtheta_samples: 20
  #controller_frequency: 10.0

  # Trajectory scoring parameters
  meter_scoring: true # Whether the gdist_scale and pdist_scale parameters should assume that goal_distance and path_distance are expressed in units of meters or cells. Cells are assumed by default (false).
  occdist_scale: 0.01 #0.2 #The weighting for how much the controller should attempt to avoid obstacles. default 0.01
  pdist_scale: 0.6 #0.75  #     The weighting for how much the controller should stay close to the path it was given . default 0.6
  gdist_scale: 0.8 #2.0 #     The weighting for how much the controller should attempt to reach its local goal, also controls speed  default 0.8

  heading_lookahead: 0.325  #How far to look ahead in meters when scoring different in-place-rotation trajectories
  heading_scoring: false  #Whether to score based on the robot's heading to the path or its distance from the path. default false
  heading_scoring_timestep: 0.8   #How far to look ahead in time in seconds along the simulated trajectory when using heading scoring (double, default: 0.8)
  dwa: true #Whether to use the Dynamic Window Approach (DWA)_ or whether to use Trajectory Rollout
  simple_attractor: false
  publish_cost_grid_pc: true  

  # Oscillation Prevention Parameters
  oscillation_reset_dist: 0.25 #How far the robot must travel in meters before oscillation flags are reset (double, default: 0.05)
  escape_reset_dist: 0.1
  escape_reset_theta: 0.1
  