# Publish all joint states -----------------------------------
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50  

# Velocity Controllers ---------------------------------------
front_left_velocity_controller:
  type: effort_controllers/JointVelocityController
  joint: front_left_wheel
  pid: {p: 0.3, i: 0.0, d: 0.0}
front_right_velocity_controller:
  type: effort_controllers/JointVelocityController
  joint: front_right_wheel
  pid: {p: 0.3, i: 0.0, d: 0.0}
mid_left_velocity_controller:
  type: effort_controllers/JointVelocityController
  joint: mid_left_wheel
  pid: {p: 0.3, i: 0.0, d: 0.0}
mid_right_velocity_controller:
  type: effort_controllers/JointVelocityController
  joint: mid_right_wheel
  pid: {p: 0.3, i: 0.0, d: 0.0}
back_left_velocity_controller:
  type: effort_controllers/JointVelocityController
  joint: back_left_wheel
  pid: {p: 0.3, i: 0.0, d: 0.0}
back_right_velocity_controller:
  type: effort_controllers/JointVelocityController
  joint: back_right_wheel
  pid: {p: 0.3, i: 0.0, d: 0.0}
main_lidar_velocity_controller:
  type: effort_controllers/JointVelocityController
  joint: main_lidar
  pid: {p: 0.1, i: 0.0, d: 0.0}